.github/workflows/build.yaml

Add a rudimentary GitHub workflow to build the sources with `tsc` for each push and pull request.

Add GitHub workflow for build

---

src/App.test.tsx
src/actions/index.ts
src/actions/types.ts
src/artifact.ts
src/components/App.tsx
src/components/ArtifactDetailedInfo.tsx
src/components/ArtifactKaiState.tsx
src/components/ArtifactStatesList.tsx
src/components/ArtifactsListByFilters.tsx
src/components/PageByFilters.tsx
src/components/PageByMongoField.tsx
src/components/PageCommon.tsx
src/components/PageGating.tsx
src/components/PageHelp.tsx
src/components/PageNewIssue.tsx
src/components/PageSST.tsx
src/components/PaginationToolbar.tsx
src/components/TestSuites.tsx
src/custom.module.css
src/hooks.ts
src/index.tsx
src/queries/Artifacts.ts
src/reducers/gateArtifactsReducer.ts
src/reducers/index.ts
src/reduxStore.ts
src/reportWebVitals.ts
src/routes.tsx
src/utils/artifactUtils.tsx
src/utils/artifactsTable.tsx

- Port _Gating tests_ page to TypeScript.
- Dynamic page titles.
- Code style improvements: drop default exports, …

Gating tests page

---

src/components/ArtifactStatesList.tsx
src/components/GatingStatus.tsx
src/components/PageByMongoField.tsx
src/components/PageCommon.tsx
src/components/PageGating.tsx
src/components/PageHeader.tsx

- Drop unused variables.
- Add missing variables to `useEffect()` dependencies.

Fix eslint warnings

---

src/components/PageHelp.tsx

Update upstream source links

---

src/components/TestSuites.tsx
src/testsuite.test.ts
src/testsuite.ts

Display test case architecture label

---

src/components/ArtifactKaiState.tsx

Add links to run details and logs

---

src/testsuite.test.ts
src/testsuite.ts

Handle missing properties in a test case

---

src/components/ArtifactGreenwaveState.tsx

After review this seems to be better worded.
@testing-farm pls review
Signed-off-by: Miroslav Vadkerti <mvadkert@redhat.com>

Improve Leapp missing test help

---

src/artifact.ts
src/utils/stages_states.ts

OSCI-3605: consolidate kai-GW mapping based on message id

---

src/components/ArtifactGreenwaveKaiState.tsx
src/components/ArtifactGreenwaveState.tsx
src/components/ArtifactStatesList.tsx

osci3617: respect resultOutcome

---

src/components/TestSuites.tsx

OSCI-3713: null checking of array using question mark break

---

src/components/WaiveForm.tsx

New look of waiver form after revamp.
`Reference: OSCI-3542`

Revamp waiver form

---

src/components/ArtifactGreenwaveKaiState.tsx
src/components/ArtifactGreenwaveState.tsx
src/components/ArtifactKaiState.tsx
src/components/MetadataInfo.tsx
src/custom.module.css
src/queries/Metadata.ts
src/types.ts
src/utils/artifactUtils.tsx

Show metadata for all states

---

src/actions/index.tsx
src/artifact.ts
src/components/PageByFilters.tsx
src/config.tsx
src/utils/artifactUtils.tsx

OSCI-3986: process redhat-container-image

---

src/artifact.ts
src/components/ArtifactsListByFilters.tsx
src/utils/artifactUtils.tsx

osci-4057: greenwave decision for container-images

---

Dockerfile

osci-4216: update permission in Dockerfile

---

src/components/GatingStatus.tsx

Follow-up to #48.
Reference: OSCI-4266

Fix counter of gating tests

---

src/components/PageMetadataEdit.tsx
src/components/WaiveForm.tsx
src/types.ts

I am not sure about approach how metadata in waive form are fetched. (First time doing it :smile: )

Add metadata for waive warning message

---

src/components/GatingStatus.tsx

Do not show zero counts in gating counter

---

src/artifact.ts
src/components/ArtifactDetailedInfo.tsx
src/config.tsx
src/queries/Errata.ts

OSCI-4011: display linked Errata advisories

---

.github/workflows/build.yaml

Update Node.js in check workflow to version 18

---

COPYING
README.md
package-lock.json
package.json

- List contributors in `package.json`.
- Specify license in `package.json` as LGPL v3.0 or later.
- Create `COPYING` file with the full license text.

Add license information

---

src/artifact.ts
src/components/ArtifactDetailedInfo.tsx
src/queries/Artifacts.ts
src/types.ts

@mgrabovsky this PR is ready for review and merge.

osci-4645: add Errata Automation code

---

src/components/ArtifactDetailedInfo.tsx

See the related Errata Tool Automation [merge request][1] for details.
[1]: https://gitlab.cee.redhat.com/osci/errata-automation/-/merge_requests/252/

Check bugs list for non-emptiness to avert a bug in ETA

---

src/components/PageMetadataList.tsx

Fix page links on metadata page

---

src/components/MetadataInfo.tsx
src/components/PageMetadataEdit.tsx
src/components/PageMetadataList.tsx
src/types.ts

Support Slack channel URL in metadata
