- .eslintrc
- src/components/ArtifactDetailedInfo.tsx
- src/components/ArtifactGreenwaveState.tsx
- src/components/ArtifactKaiState.tsx
- src/components/ArtifactState.tsx
- src/components/PageByMongoField.tsx
- src/components/PageNewIssue.tsx
- src/components/TestSuites.tsx
- src/custom.module.css
- src/types.ts
- src/utils/artifactUtils.tsx
- src/utils/artifactsTable.tsx
- src/utils/stages_states.ts
Summary of substantial changes in this patch set:
- Switch out a couple of icons, mainly to conform with Patternfly recommendations.
- Display status icons (green check mark, red cross, etc.) in place of the letter „t“ in test results.
- Remove labels of test outcomes. These labels only duplicate in a textual form the information provided by the status icons.
- A couple of code style improvements.
Most of these changes are just ports from downstream.
> A handful of backports

- README.md
- src/components/App.tsx
- src/config.tsx
Allow developers to override the URL of the GraphQL server endpoint via the `REACT_APP_GRAPHQL_SERVER_URL` environment variable. If it's not set, default to `/graphql`.
One may use the `.env.local` file in the project root to set the variable. See the Create React App [documentation][1] for more info.
[1]: https://create-react-app.dev/docs/adding-custom-environment-variables/
> Allow overriding GraphQL URL via env variable

- src/components/ArtifactGreenwaveKaiState.tsx
- src/components/ArtifactGreenwaveState.tsx
- src/components/ArtifactKaiState.tsx
- src/custom.module.css
- src/types.ts
- src/utils/artifactUtils.tsx
This change adds a documentation button to the header of individual test results.
Preview:
Reference: OSCI-3201
> Add docs button to result header

- .github/workflows/build-image.yaml
To procceed with https://issues.redhat.com/browse/OSCI-3339 we need to somehow mark stable images.
This CI allows to convert git-tag to container-tags.
> Tag container images with git-tag-name

- src/components/ArtifactGreenwaveState.tsx
AFAIK the test has different name for RHEL9, document
it for better user experience.
Signed-off-by: Miroslav Vadkerti <mvadkert@redhat.com>
> Document compose CI test RHEL9 variant

- src/components/ArtifactGreenwaveState.tsx
Reverts fedora-ci/ciboard#25
Give prio to https://github.com/fedora-ci/ciboard/pull/25
1. Both names are still used as far as I know, and
2. we now have the same name twice in a row.
> Revert "Update helper text to rename compose-ci to test-compose"

- src/components/ArtifactGreenwaveKaiState.tsx
- src/utils/artifactUtils.tsx
Decide which icon to show based on Greenwave's point of view preferentially. Whenver a result is failed from gating POV, show the red "failed" icon.
See also discussion in OSCI-3546.
> Fix icon for combined results

- src/components/TestSuites.tsx
Fix display of detailed info from the `test-outputs` field from the results xunit. This bug was caused by an improper inspection of the test case results object. As a fix, use TypeScript features in place of an opaque Lodash
function to inspect objects.
Reference: OSCI-3636
> Fix display of test outputs from xunit

- src/components/TestSuites.tsx
- src/testsuite.test.ts
- src/testsuite.ts
It looks like we need to handle undefined values more carefully around here. Follow-up to 5b6842f.
Reference: OSCI-3636
> Improve types and handling of undefined's

- src/components/ArtifactsListByFilters.tsx
Optional chaining is added for data artifacts check, to prevent uncaught error and blank page for dashboard page.
Reference: OSCI-1484
> Fix blank page on regexp error

- src/artifact.ts
- src/components/ArtifactDetailedInfo.tsx
- src/components/ExternalLink.tsx
- src/config.tsx
- src/custom.module.css
- src/queries/Artifacts.ts
- src/utils/artifactUtils.test.ts
- src/utils/artifactUtils.tsx
Extend the build info component for artifacts to display information on module builds.
Reference: OSCI-3467
Related: fedora-ci/ciboard-server#4
> Extend build info component for MBS

- src/components/PageHelp.tsx
Howdy,
Proposing to add basic GraphQL information under the help page as an additional resource under the "search" category.
Currently, there is no "straightforward" way for a user to deduce that the current dashboard instance has an API 'endpoint" from the help page. Pointing them in the right direction by explicitly mentioning the GraphQL background (and the appended link) would be of great help.
Proposing this as I got caught in a wild goose chase trying to figure out where "an API" was. Sorry if this seems trivial.
Thanks in advance.
> Add GraphQL query info to #help page

- src/components/GatingStatus.tsx
Decrease the satisfied counter by 1 since the 'fetched-gating-yaml' task isn't displayed in UI.
> fix: Adjust "OK" counter to match displayed results

- .github/dependabot.yml
Adding Dependabot or a similar service could help manage the dependencies of `ciboard`. Currently, there are quite a few of outdated packages with security vulnerabilities:
Also, enabling Dependabot Security Alerts could help you to identify vulnerable packages sooner.
Related to:
- #6 
- #47
> Dependabot - keep dependencies up to date

- .github/workflows/build-image.yaml
- .github/workflows/build.yaml
The `checkout` and `setup-node` actions should be upgraded to their latest version. See the GitHub blog [1] for details.
[1]: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/
> Update GitHub Action versions

- .eslintrc
- package.json
- src/actions/index.tsx
- src/components/ArtifactsListByFilters.tsx
- src/components/PageByMongoField.tsx
It is a good practice to allow `tsc` to infer the type from the assigned value. Eslint can help with enforcing this practice.
> Disallow explicit type declarations for variables or parameters initialized to a `number` / `string` / `boolean`

- src/testsuite.ts
Due to missing input validation, the properties of a test case obtained from the results xunit may be in a unexpected format. This change is a hotfix to make sure that we only accept correctly formatted data when displaying the results.
Reference: OSCI-4301
> Fix undefined value error in test suite display

- src/artifact.ts
- src/components/ArtifactGreenwaveKaiState.tsx
- src/components/ArtifactGreenwaveState.tsx
This is useful mainly for the `invalid-gating-yaml` virtual test.
Reference: OSCI-4453
> Display Greenwave details if available

- src/components/ArtifactGreenwaveKaiState.tsx
- src/components/ArtifactGreenwaveState.tsx
- src/components/ArtifactKaiState.tsx
- src/components/GatingStatus.tsx
- src/components/TestSuites.tsx
- src/utils/artifactUtils.tsx
Replace the `renderStatusIcon` function with two separate icon components, `TestStatusIcon` for test statuses (passed, failed, running, missing, etc.) and `GatingStatusIcon` for gating status (red or green semaphore).
This is a small piece of refactoring that came out of my work on the redesign, but it's independent so I'm proposing it directly for main.
> Create separate components for status icons

- src/components/ArtifactDetailedInfo.tsx
Show an info alert in the "Related Advisories" tab if there are no errata linked to the build. This makes the distinction between an empty and broken or loading state much clearer.
> Add empty state for related advisories

- src/utils/xunitParser.ts
Treat the `needs_inspection` result in a test case the same as the `error` result. This groups these results together and displays the yellow exclamation-triangle icon next to them to make them prominent in the UI.
Reference: OSCI-4096
> Treat needs_inspection test case same as error

- src/components/GatingStatus.tsx
- src/components/PageByMongoField.tsx
- src/queries/Artifacts.ts
- Add a type for the result of the `ArtifactsComplete` query so that we get more type checking coverage.
- Switch the order of unsatisfied and satisfied counts in the gating status summary and shorten the text to make it easier to skim.
- Make the `isLoading` prop of the component optional.
> A few small code improvements

- package.json
- src/components/ArtifactDetailedInfo.tsx
- src/components/PageResultsNew/BuildInfo.tsx
- src/components/PageResultsNew/DetailsDrawer.tsx
- src/components/PageResultsNew/Header.tsx
- src/components/PageResultsNew/TestResultsTable.tsx
- src/components/PageResultsNew/TestSuitesAccordion.tsx
- src/components/PageResultsNew/fakeData.ts
- src/components/PageResultsNew/index.css
- src/components/PageResultsNew/index.tsx
- src/components/PageResultsNew/types.ts
- src/custom.module.css
- src/routes.tsx
- src/utils/artifactUtils.tsx
- src/utils/timeUtils.test.ts
- src/utils/timeUtils.ts
In this checkpoint, the page now shows real data for RPM builds:
- NVR, gating tag and gating status, build time, commit information, tags and tagging history, and related advisories;
- list of real test results in the results table (name and status only for now).
Reference: OSCI-4226
> Results page redesign, checkpoint 2

- package-lock.json
- package.json
- src/components/PageByFilters.tsx
- src/components/PageCommon.tsx
- src/slices/filtersSlice.ts
- Fix filters not working (OSCI-5140)
- Upgrade react-router-dom
- Fix code style in filters Redux slice
- Update last bit of code after React Redux 8 & Redux Toolkit migration
> Fix filters in URL on search page

- src/components/PageResultsNew/TestResultsTable.tsx
Improve the splitting of tests into the groups awaited/failed/passed. Consider the original outcome as well as waiving status when doing the splitting. Waived tests are always passing from the point of gating.
> Improve splitting of tests into groups
